In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import necessary libraries

In [3]:
import sklearn

In [5]:
!pip install scikit-image


  Using cached imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.9 MB 16.5 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.9 MB 14.0 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.9 MB 18.6 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 18.5 MB/s eta 0:00:00
Using cached imageio-2.37.0-py3-none-any.whl (315 kB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)

   ---------------------------------------- 0/4 [tifffile]
   ---------------------------------------- 0/4 [tifffile]
   ---------- ----------------------------- 1/4 [lazy-loader]
   -------------------- ------------------- 2/4 [imageio]
   -------------------- ------------------- 2/4 [imageio]
   -------------------- ------------------- 2/4 [imageio]
   -------------------

In [6]:
from skimage.feature import hog
from skimage.transform import resize

In [7]:
folder_dogs='Train/DOG'

In [8]:
import cv2

In [17]:
import os
image_paths = [os.path.join(folder_dogs, fname)
               for fname in os.listdir(folder_dogs)
               if fname.lower().endswith(('.jpg', '.jpeg', '.png'))

               ]
#gettting path name from each image so we can use cv2.imread to get the image and use opencv to transform


In [20]:
x=[]
y=[]
for image_path in image_paths:
    image=cv2.imread(image_path)
    image_gs=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    resized_image=resize(image_gs, (64, 128))
    features=hog(resized_image, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=False)
    x.append(features) #creating a list x which is a 2nd order matrix where we keep appending a list of numbers from hog so each line represents one image
    y.append(1)#this list denotes the label  so 1 represents dog
    
#using sklearns hog feature to convert image to numeric data
 

In [22]:
x

[array([0.29667431, 0.01461804, 0.03824975, ..., 0.00615484, 0.02790484,
        0.03826688], shape=(3780,)),
 array([0.26092229, 0.26092229, 0.26092229, ..., 0.27292206, 0.10390196,
        0.02862516], shape=(3780,)),
 array([0.11880476, 0.05363265, 0.10619194, ..., 0.01860734, 0.00073187,
        0.00093919], shape=(3780,)),
 array([0.18602895, 0.08294339, 0.13013949, ..., 0.04851524, 0.0462362 ,
        0.05568926], shape=(3780,)),
 array([0.28209632, 0.028044  , 0.01096148, ..., 0.22816489, 0.19694443,
        0.10352153], shape=(3780,)),
 array([0.16594388, 0.06115734, 0.15480086, ..., 0.02841548, 0.01959879,
        0.0372462 ], shape=(3780,)),
 array([0.17335499, 0.03008584, 0.01037547, ..., 0.04256198, 0.05631378,
        0.03466362], shape=(3780,)),
 array([0.12860765, 0.18730213, 0.22072354, ..., 0.        , 0.03949911,
        0.11805261], shape=(3780,)),
 array([0.23906523, 0.16508822, 0.12590339, ..., 0.1817962 , 0.09866464,
        0.04761814], shape=(3780,)),
 array([0.

In [23]:
y

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [24]:
folder_cat='Train/CAT'

In [27]:
image_cat_path=[os.path.join(folder_cat, fname)
                for fname in os.listdir(folder_cat)
                if fname.lower().endswith(('.jpg'))
               ]

In [28]:

for path in image_cat_path:
    image=cv2.imread(path)
    image_gs=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    resized=resize(image_gs, (64, 128))
    features=hog(resized, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=False)
    x.append(features)
    y.append(0)
    #same as before but 0 is label for cat

In [29]:
x=np.array(x)
y=np.array(y)
#converting the lists to numpy arrays

In [30]:
from sklearn.utils import shuffle
x, y= shuffle(x, y, random_state=32)
#shuffling the dataset with corresponding x and y together so model learns better

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2)
#splitting 20% of data for testing 

In [36]:
class SVM:

    def __init__(self, learning_rate=0.001, lambda_param=0.01, iters=100):
        self.lr = learning_rate
        self.lambda_param = lambda_param
        self.iters = iters
        self.w = None
        self.b = None

    def fit(self, x, y):
        n_samples, n_features = x.shape

        y_ = np.where(y <= 0, -1, 1)

        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.iters):
            for idx, x_i in enumerate(x):
                condition = y_[idx] * (np.dot(x_i, self.w) - self.b) >= 1
                if condition:
                    self.w -= self.lr * (2 * self.lambda_param * self.w)
                else:
                    self.w -= self.lr * (2 * self.lambda_param * self.w - np.dot(x_i, y_[idx]))
                    self.b -= self.lr * y_[idx]


    def predict(self, x):
        approx = np.dot(x, self.w) - self.b
        if approx<0:
            return 0;
        else:
            return 1;
        #creation of own SVM model using numpy

In [37]:
model=SVM()

In [38]:
model.fit(x_train, y_train) #training model

In [40]:
c=0
for i in range(y_test.shape[0]):
    p=model.predict(x_test[i])
    if p==y_test[i]:
        c=c+1;
accuracy=(c*100)/(y_test.shape[0]) #testing model and calculating accuracy

In [41]:
print("Accuracy is ", accuracy)

Accuracy is  69.41789748045178


In [43]:
from sklearn.svm import SVC #importing SVM model from sklearn

In [50]:
model_cv=SVC(kernel='rbf', gamma=0.05, C=0.1) #setting kernel to non linear kernel 

In [51]:
model_cv.fit(x_train, y_train)#training model

SVC(C=1, gamma=0.05)

In [53]:
c=0
p=model_cv.predict(x_test)
for i in range(y_test.shape[0]):
    if p[i]==y_test[i]:
        c=c+1;
accuracy_new=(c*100)/(y_test.shape[0])
print("New accuracy is ", accuracy_new) #testing and calculating new accuracy

New accuracy is  70.89487402258905
